services:
  - type: web
    name: voice-agent
    env: python
    region: singapore              # closest to AU; change if you prefer
    plan: starter                  # avoid Free sleeping for production
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

    healthCheckPath: /health       # served by main.py's process_request()

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9              # stable with websockets==11.x
      - key: DEEPGRAM_API_KEY
        sync: false                # set this in Render → Environment

    # Optional: keep more logs and slightly longer timeouts for WS apps
    # (These are safe defaults; adjust as you learn your traffic profile.)
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    runtime:
      cpuThreshold: 85
      memoryThreshold: 85










