services:
  - type: web
    name: riverstone-voice-agent
    env: python
    plan: starter
    region: oregon
    rootDir: Voice Agent
    buildCommand: pip install -r requirements.txt
    startCommand: python serve.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DEEPGRAM_API_KEY
        sync: false   # add this in the Render Dashboard → Environment




