services:
  # ------------------------
  # API Service (HTTP layer)
  # ------------------------
  - type: web
    name: ai-voice-sales-agent-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free        # or starter/standard depending on usage
    envVars:
      - key: RUN_MODE
        value: http
      - key: PUBLIC_BASE_URL
        value: https://ai-voice-sales-agent-api.onrender.com
      - key: PUBLIC_WS_URL
        value: wss://ai-voice-sales-agent-ws.onrender.com/twilio
      - key: DEEPGRAM_API_KEY
        sync: false    # mark secret, set in Render dashboard

  # ------------------------
  # WebSocket Service (Twilio Media Stream bridge)
  # ------------------------
  - type: web
    name: ai-voice-sales-agent-ws
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: RUN_MODE
        value: ws
      - key: PUBLIC_BASE_URL
        value: https://ai-voice-sales-agent-api.onrender.com
      - key: PUBLIC_WS_URL
        value: wss://ai-voice-sales-agent-ws.onrender.com/twilio
      - key: DEEPGRAM_API_KEY
        sync: false


