services:
  - type: web
    name: voice-agent
    env: python
    region: singapore           # closer to Australia; pick another if you prefer
    plan: starter               # or free/pro as you need
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DEEPGRAM_API_KEY
        sync: false             # set in Render dashboard as a secret        
      - key: PYTHON_VERSION
        value: 3.11.9           # known-good with websockets 11.x








